name: guppy
channels:
  - pyviz
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - panel=0.13.1
  - holoviews=1.15.0
  - datashader=0.13.0
  - h5py==3.7.0
  - scipy==1.10.0
  - pytables=3.6.1
  - firefox=100.0
  - selenium=4.6.0
  - geckodriver=0.30.0
