name: guppy
channels:
  - numba
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async_generator=1.10
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - colorcet=3.0.1
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.4.1
  - dask-core=2023.4.1
  - datashader=0.13.0
  - datashape=0.5.4
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.4.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.4.0
  - geckodriver=0.32.0
  - giflib=5.2.1
  - h11=0.14.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - holoviews=1.15.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - llvmlite=0.36.0
  - locket=1.0.0
  - lxml=4.9.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - msgpack-python=1.0.3
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numba=0.53.1
  - numexpr=2.8.4
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1t
  - outcome=1.2.0
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - panel=0.13.1
  - param=1.13.0
  - parso=0.8.3
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyct=0.5.0
  - pyct-core=0.5.0
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-lmdb=1.4.1
  - python_abi=3.9
  - pytz=2022.7
  - pyviz_comms=2.2.1
  - pyyaml=6.0
  - pyzmq=25.0.2
  - readline=8.2
  - requests=2.29.0
  - scipy=1.10.0
  - selenium=4.6.0
  - send2trash=1.8.0
  - setuptools=66.0.0
  - six=1.16.0
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tblib=1.7.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - trio=0.22.0
  - trio-websocket=0.9.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - wsproto=1.2.0
  - xarray=2022.11.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5