"""Generate stubbed testing data from the full testing_data directory.

Run from the project root:
    python scripts/create_stubbed_testing_data.py

Stub durations are hard-coded per session. For sessions with TTL events, the
duration was chosen to capture at least 5 complete TTL pulses (rising and
falling edges both within the stub window for waveform-based formats).
Sessions without TTL events use 1.0 second.

A duration of None means the session is copied as-is without any truncation.
Use this for sessions that are already small enough that stubbing causes problems.

Note: NpmRecordingExtractor.stub() copies the raw source folder and truncates
raw NPM CSVs. Intermediate per-channel CSVs (chev/chod/event) are not present
in the stub — they must be regenerated by calling discover_events_and_flags()
on the stub folder before reading.
"""

import shutil
from pathlib import Path

import numpy as np
import pandas as pd

from guppy.extractors.base_recording_extractor import BaseRecordingExtractor
from guppy.extractors.csv_recording_extractor import CsvRecordingExtractor
from guppy.extractors.doric_recording_extractor import DoricRecordingExtractor
from guppy.extractors.npm_recording_extractor import NpmRecordingExtractor
from guppy.extractors.tdt_recording_extractor import TdtRecordingExtractor

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent
TESTING_DATA = PROJECT_ROOT / "testing_data"
STUBBED_TESTING_DATA = PROJECT_ROOT / "stubbed_testing_data"


# ---------------------------------------------------------------------------
# Session configurations
# ---------------------------------------------------------------------------
# Each entry: (extractor_instance, stub_duration_in_seconds, destination_path)
# Durations were determined by running the full recording and finding the first
# TTL event timestamp, then adding a 0.1 s buffer.


def _sessions() -> list[tuple[BaseRecordingExtractor, float | None, Path]]:
    tdt = TESTING_DATA / "SampleData_Clean"
    artifacts = TESTING_DATA / "SampleData_with_artifacts"
    doric = TESTING_DATA / "SampleData_Doric"
    npm = TESTING_DATA / "SampleData_Neurophotometrics"
    csv = TESTING_DATA / "SampleData_csv"

    dest_tdt = STUBBED_TESTING_DATA / "tdt"
    dest_doric = STUBBED_TESTING_DATA / "doric"
    dest_npm = STUBBED_TESTING_DATA / "npm"
    dest_csv = STUBBED_TESTING_DATA / "csv"

    return [
        # TDT — 5th TTL (PrtN) at ~157.4 s relative
        (
            TdtRecordingExtractor(str(tdt / "Photo_63_207-181030-103332")),
            157.5,
            dest_tdt / "Photo_63_207-181030-103332",
        ),
        # TDT — 5th TTL (PAB/) at ~215.8 s relative
        (
            TdtRecordingExtractor(str(tdt / "Photometry-161823")),
            215.9,
            dest_tdt / "Photometry-161823",
        ),
        # TDT — 5th TTL (PrtN) at ~184.2 s relative
        (
            TdtRecordingExtractor(str(artifacts / "Photo_048_392-200728-121222")),
            184.3,
            dest_tdt / "Photo_048_392-200728-121222",
        ),
        # Doric V1 — 5th TTL pulse (DI--O-1) ends at ~115.1 s
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_1"),
                {"AIn-1 - Raw": "control", "AIn-2 - Raw": "signal", "DI--O-1": "ttl"},
            ),
            115.2,
            dest_doric / "sample_doric_1",
        ),
        # Doric CSV — 5th TTL pulse (DI/O-1) ends at ~77.9 s
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_2"),
                {"AIn-1 - Dem (ref)": "control", "AIn-1 - Dem (da)": "signal", "DI/O-1": "ttl"},
            ),
            78.0,
            dest_doric / "sample_doric_2",
        ),
        # Doric V6 — 5th TTL (DigitalIO/CAM1) at ~0.1 s; 1.0 s retains many TTLs
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_3"),
                {"CAM1_EXC1/ROI01": "control", "CAM1_EXC2/ROI01": "signal", "DigitalIO/CAM1": "ttl"},
            ),
            16.0,
            dest_doric / "sample_doric_3",
        ),
        # Doric V1 — no TTL events
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_4"),
                {"Series0001/AIN01xAOUT01-LockIn": "control", "Series0001/AIN01xAOUT02-LockIn": "signal"},
            ),
            16.0,
            dest_doric / "sample_doric_4",
        ),
        # Doric V1 — no TTL events
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_5"),
                {"Series0001/AIN01xAOUT01-LockIn": "control", "Series0001/AIN01xAOUT02-LockIn": "signal"},
            ),
            16.0,
            dest_doric / "sample_doric_5",
        ),
        # CSV — 5th TTL (Sample_TTL) at ~410.9 s
        (CsvRecordingExtractor(str(csv / "sample_data_csv_1")), 411.0, dest_csv / "sample_data_csv_1"),
        # NPM v2 (LedState header) — 5th TTL (stimuli) at ~120.2 s relative
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_1")), 120.3, dest_npm / "sampleData_NPM_1"),
        # NPM v2 (LedState header, two files) — no TTL events
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_2")), 16.0, dest_npm / "sampleData_NPM_2"),
        # NPM v2 (LedState header, 4 channels) — copied as-is (small enough; stubbing causes test failures)
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_3")), None, dest_npm / "sampleData_NPM_3"),
        # NPM legacy (no header, interleaved rows) — 10th TTL (ts0) at ~577.3 s relative (5 True TTLs and 5 False TTLs)
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_4")), 578.0, dest_npm / "sampleData_NPM_4"),
        # NPM legacy (no header, interleaved rows) — copied as-is (small enough; stubbing causes test failures)
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_5")), None, dest_npm / "sampleData_NPM_5"),
    ]


# ---------------------------------------------------------------------------
# Synthetic injection CSV session
# ---------------------------------------------------------------------------
# Unlike the sessions above (truncated from real recordings), this session is
# fully synthesized so it can demonstrate baseline-epoch control fitting: the
# 465 nm signal has a sustained step-change at the injection time while the
# 405 nm isosbestic control does not. Fitting the control->signal model over
# the full trace is corrupted by the step, whereas fitting only the
# pre-injection window recovers the true relationship.

INJECTION_CSV_SAMPLING_RATE = 100.0  # Hz — kept low so the committed CSVs stay small
INJECTION_CSV_DURATION = 120.0  # s
INJECTION_TIME = 60.0  # s — signal step onset and one of the TTL pulses
INJECTION_TTL_TIMES = (20.0, 40.0, 60.0, 80.0, 100.0)  # s — 5 pulses, one at injection
# True pre-injection control->signal relationship (signal = SLOPE * control + INTERCEPT).
INJECTION_TRUE_SLOPE = 1.5
INJECTION_TRUE_INTERCEPT = 10.0
INJECTION_STEP_AMPLITUDE = 40.0  # sustained signal increase after injection


def _write_injection_csv_session(destination: Path) -> None:
    """Synthesize the injection CSV session and write its three channel CSVs."""
    rng = np.random.default_rng(200)  # deterministic — issue #200
    num_samples = int(round(INJECTION_CSV_DURATION * INJECTION_CSV_SAMPLING_RATE))
    timestamps = np.arange(num_samples) / INJECTION_CSV_SAMPLING_RATE

    # 405 nm isosbestic control: photobleaching decay + slow motion wiggle + noise. No injection step.
    bleach = 30.0 * np.exp(-timestamps / 60.0)
    motion = 2.0 * np.sin(2.0 * np.pi * 0.05 * timestamps)
    control = 100.0 + bleach + motion + rng.normal(0.0, 0.5, num_samples)

    # 465 nm signal: shares bleaching/motion via the linear relationship, plus a sustained
    # post-injection step (the effect that breaks a full-trace fit).
    step = np.where(timestamps >= INJECTION_TIME, INJECTION_STEP_AMPLITUDE, 0.0)
    signal = INJECTION_TRUE_SLOPE * control + INJECTION_TRUE_INTERCEPT + step + rng.normal(0.0, 0.5, num_samples)

    destination.mkdir(parents=True, exist_ok=True)
    for name, data in (("Sample_Control_Channel", control), ("Sample_Signal_Channel", signal)):
        sampling_rate_column = np.full(num_samples, np.nan)
        sampling_rate_column[0] = INJECTION_CSV_SAMPLING_RATE
        frame = pd.DataFrame({"timestamps": timestamps, "data": data, "sampling_rate": sampling_rate_column})
        frame.to_csv(destination / f"{name}.csv", index=False)

    pd.DataFrame({"timestamps": np.array(INJECTION_TTL_TIMES)}).to_csv(destination / "Sample_TTL.csv", index=False)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    """Generate stubbed testing data for all registered acquisition formats."""
    print(f"Writing stubbed data to: {STUBBED_TESTING_DATA}\n")
    for extractor, duration, destination in _sessions():
        modality = type(extractor).__name__.replace("RecordingExtractor", "")
        if duration is None:
            print(f"  {modality:5s} {destination.name} (copy) ...", end=" ", flush=True)
            shutil.copytree(extractor.folder_path, destination, dirs_exist_ok=True)
        else:
            print(f"  {modality:5s} {destination.name} ({duration}s) ...", end=" ", flush=True)
            extractor.stub(folder_path=destination, duration_in_seconds=duration)
        print("done")

    injection_destination = STUBBED_TESTING_DATA / "csv" / "sample_data_csv_injection_1"
    print(f"  CSV   {injection_destination.name} (synthetic) ...", end=" ", flush=True)
    _write_injection_csv_session(injection_destination)
    print("done")
    print("\nDone.")


if __name__ == "__main__":
    main()
