"""Generate stubbed testing data from the full testing_data directory.

Run from the project root:
    python scripts/create_stubbed_testing_data.py

Stub durations are hard-coded per session. For sessions with TTL events, the
duration was chosen to capture at least 5 complete TTL pulses (rising and
falling edges both within the stub window for waveform-based formats).
Sessions without TTL events use 1.0 second.

A duration of None means the session is copied as-is without any truncation.
Use this for sessions that are already small enough that stubbing causes problems.

Note: NpmRecordingExtractor.stub() copies the raw source folder and truncates
raw NPM CSVs. Intermediate per-channel CSVs (chev/chod/event) are not present
in the stub — they must be regenerated by calling discover_events_and_flags()
on the stub folder before reading.
"""

import shutil
from pathlib import Path

import numpy as np
import pandas as pd

from guppy.extractors.base_recording_extractor import BaseRecordingExtractor
from guppy.extractors.csv_recording_extractor import CsvRecordingExtractor
from guppy.extractors.doric_recording_extractor import DoricRecordingExtractor
from guppy.extractors.npm_recording_extractor import NpmRecordingExtractor
from guppy.extractors.tdt_recording_extractor import TdtRecordingExtractor

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent
TESTING_DATA = PROJECT_ROOT / "testing_data"
STUBBED_TESTING_DATA = PROJECT_ROOT / "stubbed_testing_data"


# ---------------------------------------------------------------------------
# Session configurations
# ---------------------------------------------------------------------------
# Each entry: (extractor_instance, stub_duration_in_seconds, destination_path)
# Durations were determined by running the full recording and finding the first
# TTL event timestamp, then adding a 0.1 s buffer.


def _sessions() -> list[tuple[BaseRecordingExtractor, float | None, Path]]:
    tdt = TESTING_DATA / "SampleData_Clean"
    artifacts = TESTING_DATA / "SampleData_with_artifacts"
    doric = TESTING_DATA / "SampleData_Doric"
    npm = TESTING_DATA / "SampleData_Neurophotometrics"
    csv = TESTING_DATA / "SampleData_csv"

    dest_tdt = STUBBED_TESTING_DATA / "tdt"
    dest_doric = STUBBED_TESTING_DATA / "doric"
    dest_npm = STUBBED_TESTING_DATA / "npm"
    dest_csv = STUBBED_TESTING_DATA / "csv"

    return [
        # TDT — 5th TTL (PrtN) at ~157.4 s relative
        (
            TdtRecordingExtractor(str(tdt / "Photo_63_207-181030-103332")),
            157.5,
            dest_tdt / "Photo_63_207-181030-103332",
        ),
        # TDT — 5th TTL (PAB/) at ~215.8 s relative
        (
            TdtRecordingExtractor(str(tdt / "Photometry-161823")),
            215.9,
            dest_tdt / "Photometry-161823",
        ),
        # TDT — 5th TTL (PrtN) at ~184.2 s relative
        (
            TdtRecordingExtractor(str(artifacts / "Photo_048_392-200728-121222")),
            184.3,
            dest_tdt / "Photo_048_392-200728-121222",
        ),
        # Doric V1 — 5th TTL pulse (DI--O-1) ends at ~115.1 s
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_1"),
                {"AIn-1 - Raw": "control", "AIn-2 - Raw": "signal", "DI--O-1": "ttl"},
            ),
            115.2,
            dest_doric / "sample_doric_1",
        ),
        # Doric CSV — 5th TTL pulse (DI/O-1) ends at ~77.9 s
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_2"),
                {"AIn-1 - Dem (ref)": "control", "AIn-1 - Dem (da)": "signal", "DI/O-1": "ttl"},
            ),
            78.0,
            dest_doric / "sample_doric_2",
        ),
        # Doric V6 — 5th TTL (DigitalIO/CAM1) at ~0.1 s; 1.0 s retains many TTLs
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_3"),
                {"CAM1_EXC1/ROI01": "control", "CAM1_EXC2/ROI01": "signal", "DigitalIO/CAM1": "ttl"},
            ),
            16.0,
            dest_doric / "sample_doric_3",
        ),
        # Doric V1 — no TTL events
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_4"),
                {"Series0001/AIN01xAOUT01-LockIn": "control", "Series0001/AIN01xAOUT02-LockIn": "signal"},
            ),
            16.0,
            dest_doric / "sample_doric_4",
        ),
        # Doric V1 — no TTL events
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_5"),
                {"Series0001/AIN01xAOUT01-LockIn": "control", "Series0001/AIN01xAOUT02-LockIn": "signal"},
            ),
            16.0,
            dest_doric / "sample_doric_5",
        ),
        # CSV — 5th TTL (Sample_TTL) at ~410.9 s
        (CsvRecordingExtractor(str(csv / "sample_data_csv_1")), 411.0, dest_csv / "sample_data_csv_1"),
        # NPM v2 (LedState header) — 5th TTL (stimuli) at ~120.2 s relative
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_1")), 120.3, dest_npm / "sampleData_NPM_1"),
        # NPM v2 (LedState header, two files) — no TTL events
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_2")), 16.0, dest_npm / "sampleData_NPM_2"),
        # NPM v2 (LedState header, 4 channels) — copied as-is (small enough; stubbing causes test failures)
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_3")), None, dest_npm / "sampleData_NPM_3"),
        # NPM legacy (no header, interleaved rows) — 10th TTL (ts0) at ~577.3 s relative (5 True TTLs and 5 False TTLs)
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_4")), 578.0, dest_npm / "sampleData_NPM_4"),
        # NPM legacy (no header, interleaved rows) — copied as-is (small enough; stubbing causes test failures)
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_5")), None, dest_npm / "sampleData_NPM_5"),
    ]


# ---------------------------------------------------------------------------
# Synthetic injection CSV session
# ---------------------------------------------------------------------------
# Unlike the sessions above (truncated from real recordings), this session is
# fully synthesized so it can demonstrate baseline-epoch control fitting: the
# 465 nm signal has a sustained step-change at the injection time while the
# 405 nm isosbestic control does not. Fitting the control->signal model over
# the full trace is corrupted by the step, whereas fitting only the
# pre-injection window recovers the true relationship.
#
# The signal walks through the three epochs of a bolus-injection experiment, so it
# also serves the tonic/basal analysis tests: a flat baseline, a sustained plateau
# once the drug is on board, and an exponential clearance back toward baseline. The
# rise stays instantaneous — a bolus reaches the tissue fast relative to this
# timebase, and it is the discontinuity that breaks a full-trace control fit.

INJECTION_CSV_SAMPLING_RATE = 100.0  # Hz — kept low so the committed CSVs stay small
# Three equal 60 s phases: baseline, drug on board, clearance.
INJECTION_CSV_DURATION = 180.0  # s
INJECTION_TIME = 60.0  # s — signal step onset and one of the TTL pulses
WASHOUT_TIME = 120.0  # s — drug clearance begins; also a TTL pulse
WASHOUT_TAU = 6.0  # s — clearance is ~95% done within 18 s, so most of the phase is a flat plateau
# Clearance is incomplete, so the washout phase settles at its own level rather than back
# onto the baseline. Three separated plateaus are the point of the session.
WASHOUT_RESIDUAL_FRACTION = 0.25
INJECTION_TTL_TIMES = tuple(float(t) for t in range(20, 180, 20))  # 20 s grid; 60 s = injection, 120 s = washout
# True pre-injection control->signal relationship (signal = SLOPE * control + INTERCEPT).
INJECTION_TRUE_SLOPE = 1.5
INJECTION_TRUE_INTERCEPT = 10.0
INJECTION_STEP_AMPLITUDE = 40.0  # signal increase held between injection and washout


def _write_injection_csv_session(destination: Path) -> None:
    """Synthesize the injection CSV session and write its three channel CSVs."""
    rng = np.random.default_rng(200)  # deterministic — issue #200
    num_samples = int(round(INJECTION_CSV_DURATION * INJECTION_CSV_SAMPLING_RATE))
    timestamps = np.arange(num_samples) / INJECTION_CSV_SAMPLING_RATE

    # 405 nm isosbestic control: photobleaching decay + slow motion wiggle + noise. No injection step.
    bleach = 30.0 * np.exp(-timestamps / 60.0)
    motion = 2.0 * np.sin(2.0 * np.pi * 0.05 * timestamps)
    control = 100.0 + bleach + motion + rng.normal(0.0, 0.5, num_samples)

    # 465 nm signal: shares bleaching/motion via the linear relationship, plus the drug
    # effect — a step up at injection (what breaks a full-trace fit), held while the drug
    # is on board, then cleared exponentially from the washout time.
    step = np.where(timestamps >= INJECTION_TIME, INJECTION_STEP_AMPLITUDE, 0.0)
    decay = np.exp(-np.maximum(timestamps - WASHOUT_TIME, 0.0) / WASHOUT_TAU)
    clearance = WASHOUT_RESIDUAL_FRACTION + (1.0 - WASHOUT_RESIDUAL_FRACTION) * decay
    drug_effect = step * np.where(timestamps >= WASHOUT_TIME, clearance, 1.0)
    signal = INJECTION_TRUE_SLOPE * control + INJECTION_TRUE_INTERCEPT + drug_effect + rng.normal(0.0, 0.5, num_samples)

    destination.mkdir(parents=True, exist_ok=True)
    for name, data in (("Sample_Control_Channel", control), ("Sample_Signal_Channel", signal)):
        sampling_rate_column = np.full(num_samples, np.nan)
        sampling_rate_column[0] = INJECTION_CSV_SAMPLING_RATE
        frame = pd.DataFrame({"timestamps": timestamps, "data": data, "sampling_rate": sampling_rate_column})
        frame.to_csv(destination / f"{name}.csv", index=False)

    pd.DataFrame({"timestamps": np.array(INJECTION_TTL_TIMES)}).to_csv(destination / "Sample_TTL.csv", index=False)


# ---------------------------------------------------------------------------
# Synthetic behavioral-covariate CSV session
# ---------------------------------------------------------------------------
# Also fully synthesized. This session carries two hand-scored behavioral covariates
# alongside the photometry, so the covariate correlation analysis has a session to run
# on and the how-to has a session to screenshot.
#
# The covariates differ in one respect only. `akinesia` drives the 465 nm signal, so it
# correlates with the per-bin metrics. `grooming` is generated independently and drives
# nothing. Both are equally slow and equally smooth, because that is the point: a score
# that is unrelated to the signal still lands at a moderate correlation over a dozen
# bins, which is what the covariate how-to warns readers to expect.
#
# The signal also carries an independent slow nuisance component. Without it, averaging
# over 50 s bins would annihilate the white noise and leave `akinesia` correlating at
# ~1.0 — a straight line that would misrepresent what this analysis produces.

COVARIATE_CSV_SAMPLING_RATE = 100.0  # Hz — kept low so the committed CSVs stay small
COVARIATE_CSV_DURATION = 600.0  # s — 12 whole bins at the 50 s bin width the consumers use
COVARIATE_SCORING_CADENCE = 25.0  # s between scores, so every bin holds two of them
COVARIATE_TRUE_SLOPE = 1.5
COVARIATE_TRUE_INTERCEPT = 10.0
# Each covariate is a sum of (amplitude, period_in_seconds, phase) sinusoids around a
# baseline, sampled and rounded to one decimal to look like a rated severity score.
AKINESIA_BASELINE = 2.5
AKINESIA_COMPONENTS = ((1.5, 260.0, 0.0), (0.7, 97.0, 1.1))
GROOMING_BASELINE = 2.0
GROOMING_COMPONENTS = ((1.2, 205.0, 2.3), (0.6, 71.0, 0.4))
COVARIATE_EFFECT_GAIN = 8.0  # signal units per akinesia point
# Slow signal variation that no covariate explains. Its amplitude was chosen so the
# nuisance contributes ~0.62 times the effect's per-bin spread, which puts the designed
# akinesia correlation near 0.85 rather than at a degenerate 1.0.
COVARIATE_NUISANCE_COMPONENTS = ((1.0, 173.0, 0.7), (0.6, 311.0, 2.9))
COVARIATE_NUISANCE_AMPLITUDE = 6.427150403216821
# Dopamine-like transients at a constant rate, so per-bin transient counts vary without
# tracking either covariate.
COVARIATE_TRANSIENT_RATE = 0.4  # Hz
COVARIATE_TRANSIENT_AMPLITUDE = 6.0
COVARIATE_TRANSIENT_TAU = 0.4  # s
COVARIATE_TTL_TIMES = tuple(float(t) for t in range(30, 600, 30))  # 30 s grid, so the PSTH tabs have events


def _slow_score(timestamps: np.ndarray, baseline: float, components: tuple) -> np.ndarray:
    """Sum sinusoidal components onto a baseline to make a smooth, slowly varying score."""
    values = np.full(timestamps.shape, float(baseline))
    for amplitude, period, phase in components:
        values += amplitude * np.sin(2.0 * np.pi * timestamps / period + phase)
    return values


def _write_covariate_csv_session(destination: Path) -> None:
    """Synthesize the behavioral-covariate CSV session and write its five CSVs."""
    rng = np.random.default_rng(425)  # deterministic — PR #425
    num_samples = int(round(COVARIATE_CSV_DURATION * COVARIATE_CSV_SAMPLING_RATE))
    timestamps = np.arange(num_samples) / COVARIATE_CSV_SAMPLING_RATE

    # 405 nm isosbestic control: photobleaching decay + slow motion wiggle + noise. It carries
    # no covariate effect, so the control fit cannot regress the effect out of the signal.
    bleach = 30.0 * np.exp(-timestamps / 200.0)
    motion = 2.0 * np.sin(2.0 * np.pi * 0.05 * timestamps)
    control = 100.0 + bleach + motion + rng.normal(0.0, 0.5, num_samples)

    akinesia = _slow_score(timestamps, AKINESIA_BASELINE, AKINESIA_COMPONENTS)
    grooming = _slow_score(timestamps, GROOMING_BASELINE, GROOMING_COMPONENTS)
    nuisance = COVARIATE_NUISANCE_AMPLITUDE * _slow_score(timestamps, 0.0, COVARIATE_NUISANCE_COMPONENTS)

    num_transients = int(round(COVARIATE_TRANSIENT_RATE * COVARIATE_CSV_DURATION))
    transient_onsets = np.sort(rng.uniform(0.0, COVARIATE_CSV_DURATION, num_transients))
    transient_span = int(6.0 * COVARIATE_TRANSIENT_TAU * COVARIATE_CSV_SAMPLING_RATE)
    transients = np.zeros(num_samples)
    for onset in transient_onsets:
        start = int(onset * COVARIATE_CSV_SAMPLING_RATE)
        decay_window = slice(start, min(start + transient_span, num_samples))
        elapsed = timestamps[decay_window] - onset
        transients[decay_window] += COVARIATE_TRANSIENT_AMPLITUDE * np.exp(-elapsed / COVARIATE_TRANSIENT_TAU)

    # 465 nm signal: the control relationship, plus the akinesia effect, plus everything
    # the covariates do not explain.
    signal = (
        COVARIATE_TRUE_SLOPE * control
        + COVARIATE_TRUE_INTERCEPT
        + COVARIATE_EFFECT_GAIN * akinesia
        + nuisance
        + transients
        + rng.normal(0.0, 0.5, num_samples)
    )

    destination.mkdir(parents=True, exist_ok=True)
    for name, data in (("Sample_Control_Channel", control), ("Sample_Signal_Channel", signal)):
        sampling_rate_column = np.full(num_samples, np.nan)
        sampling_rate_column[0] = COVARIATE_CSV_SAMPLING_RATE
        frame = pd.DataFrame({"timestamps": timestamps, "data": data, "sampling_rate": sampling_rate_column})
        frame.to_csv(destination / f"{name}.csv", index=False)

    pd.DataFrame({"timestamps": np.array(COVARIATE_TTL_TIMES)}).to_csv(destination / "Sample_TTL.csv", index=False)

    # Each covariate is its own GuPPy CSV, which is how a user supplies more than one.
    score_times = np.arange(0.0, COVARIATE_CSV_DURATION, COVARIATE_SCORING_CADENCE)
    for name, latent in (("akinesia", akinesia), ("grooming", grooming)):
        scores = np.round(np.interp(score_times, timestamps, latent), 1)
        frame = pd.DataFrame(
            {
                "timestamps": score_times,
                "data": scores,
                "sampling_rate": np.full(score_times.size, 1.0 / COVARIATE_SCORING_CADENCE),
            }
        )
        frame.to_csv(destination / f"{name}.csv", index=False)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    """Generate stubbed testing data for all registered acquisition formats."""
    print(f"Writing stubbed data to: {STUBBED_TESTING_DATA}\n")
    for extractor, duration, destination in _sessions():
        modality = type(extractor).__name__.replace("RecordingExtractor", "")
        if duration is None:
            print(f"  {modality:5s} {destination.name} (copy) ...", end=" ", flush=True)
            shutil.copytree(extractor.folder_path, destination, dirs_exist_ok=True)
        else:
            print(f"  {modality:5s} {destination.name} ({duration}s) ...", end=" ", flush=True)
            extractor.stub(folder_path=destination, duration_in_seconds=duration)
        print("done")

    injection_destination = STUBBED_TESTING_DATA / "csv" / "sample_data_csv_injection_1"
    print(f"  CSV   {injection_destination.name} (synthetic) ...", end=" ", flush=True)
    _write_injection_csv_session(injection_destination)
    print("done")

    covariate_destination = STUBBED_TESTING_DATA / "csv" / "sample_data_csv_covariate_1"
    print(f"  CSV   {covariate_destination.name} (synthetic) ...", end=" ", flush=True)
    _write_covariate_csv_session(covariate_destination)
    print("done")
    print("\nDone.")


if __name__ == "__main__":
    main()
