name: guppy_nwb_v0_1_0
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - ndx-fiber-photometry==0.1.0
    - pynwb==2.8.2
    - hdmf==3.14.6
    - ndx-events==0.2.2
    - numpy==2.2.6
