name: guppy_ndx_fiber_photometry_v0_2_ndx_events_v0_4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - ndx-events==0.4.0
    - pynwb
    - ndx-fiber-photometry
