# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "matplotlib",
#     "numpy",
# ]
# ///
"""Generate SVG figures for the fiber-photometry explanation page.

Figure 1 (technique schematic) is hand-illustrated and lives at
docs/_static/images/fiber_photometry_explainer/fig1_technique_schematic.png;
it is not generated by this script.

Two matplotlib figures are produced here:
    fig2_population_summing.svg — the bulk fluorescence signal as a
        per-timepoint sum of per-cell contributions, in two configurations:
        an ordinary heterogeneous active population, and a population with
        mixed positive- and negative-response cells (illustrating amplitude
        attenuation under opposite-polarity averaging).
    fig3_space_time_landscape.svg — a (log time x log spatial-scale)
        landscape that places fiber photometry against electrophysiology,
        two-photon imaging, and fMRI, with a gray frame marking the
        behaviourally relevant temporal range and signal-chain brackets
        along the time axis showing cellular landmarks (action potential,
        calcium influx, GCaMP variant kinetics from Chen et al. 2013).

Run with:

    uv run docs/scripts/fiber_photometry_explainer.py

Inline dependencies above let `uv run` resolve everything without needing
the surrounding project to be installed. Outputs are written directly to
docs/_static/images/fiber_photometry_explainer/.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle, Rectangle

OUT = Path(__file__).resolve().parent.parent / "_static" / "images" / "fiber_photometry_explainer"
OUT.mkdir(parents=True, exist_ok=True)

plt.rcParams.update(
    {
        "font.size": 9,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.spines.left": False,
        "axes.spines.bottom": False,
        "savefig.transparent": True,
        "figure.facecolor": "none",
        "axes.facecolor": "none",
        "axes.edgecolor": "#444444",
        "text.color": "#222222",
        # Keep SVG text editable in Inkscape rather than path-converted.
        "svg.fonttype": "none",
    }
)

COLOR_PHOTOMETRY = "#2ca02c"
COLOR_PHOTOMETRY_DARK = "#1f7a1f"
COLOR_NEGATIVE = "#d62728"
COLOR_NEGATIVE_DARK = "#7a1f1f"
COLOR_EPHYS = "#c94c8c"
COLOR_EPHYS_DARK = "#8a3360"
COLOR_TWOPHOTON = "#3b6bb0"
COLOR_TWOPHOTON_DARK = "#234a82"
COLOR_FMRI = "#d68a3a"
COLOR_FMRI_DARK = "#9a5d20"

# Photometry band on figure 3.
BAND_X0, BAND_X1 = 0.05, 10.0
BAND_Y0, BAND_Y1 = 500.0, 3000.0


def figure_2_population_summing():
    """The bulk fluorescence signal as a sum across labeled cells.

    Two configurations:
      Row 1 (Ordinary aggregation): heterogeneous active population, all
        cells responding positively with varied timing, amplitude, and width.
      Row 2 (Mixed polarities): positive plus negative-response cells,
        illustrating amplitude attenuation under partial cancellation.

    A single global legend on the right names the three line styles
    (positive-response cell, negative-response cell, photometry signal),
    keeping the per-row trace panels uncluttered.
    """
    fig = plt.figure(figsize=(13.0, 5.6))
    gs = fig.add_gridspec(
        2, 3,
        width_ratios=[1.0, 3.5, 1.3],
        hspace=0.50, wspace=0.10,
        top=0.88, bottom=0.10, left=0.05, right=0.97,
    )

    configs = [
        ("Ordinary aggregation",
         "15 cells, varied amplitudes",
         [2.5, 0.5, 1.8, 1.0, 0.3, 2.2, 1.2, 0.8, 1.5, 0.6,
          2.0, 1.0, 0.4, 1.7, 0.9],
         []),
        ("Mixed polarities",
         "15 positive + 5 negative",
         [2.0, 1.5, 1.0, 0.5, 1.8, 1.2, 0.8, 1.4, 1.0, 0.6,
          1.5, 1.1, 0.7, 1.3, 1.6],
         [1.5, 1.0, 0.7, 1.2, 0.9]),
    ]

    t = np.linspace(0, 2, 300)
    event_t = 1.0
    sigma_t = 0.14
    rng_jitter = np.random.default_rng(11)
    n_per_row = 5

    for index, (title, summary, amps_pos, amps_neg) in enumerate(configs):
        ax_cells = fig.add_subplot(gs[index, 0])
        ax_trace = fig.add_subplot(gs[index, 1])

        # Cells panel (left): green for positive-response, red for negative.
        ax_cells.set_xlim(0, 5)
        ax_cells.set_ylim(0, 3.2)
        ax_cells.set_aspect("equal")
        ax_cells.set_xticks([])
        ax_cells.set_yticks([])
        ax_cells.set_title(title, fontsize=11.5, loc="left", pad=6)
        for spine in ax_cells.spines.values():
            spine.set_visible(False)

        for i, amp in enumerate(amps_pos):
            cx = 0.5 + (i % n_per_row) * 0.9
            cy = 0.6 + (i // n_per_row) * 0.6
            r = 0.12 + 0.05 * min(amp, 3.0)
            ax_cells.add_patch(
                Circle((cx, cy), r,
                       facecolor=COLOR_PHOTOMETRY,
                       edgecolor=COLOR_PHOTOMETRY_DARK, linewidth=0.5)
            )
        for i, amp in enumerate(amps_neg):
            cx = 0.5 + (i % n_per_row) * 0.9
            cy = 2.7 - (i // n_per_row) * 0.55
            r = 0.12 + 0.05 * min(amp, 3.0)
            ax_cells.add_patch(
                Circle((cx, cy), r,
                       facecolor=COLOR_NEGATIVE,
                       edgecolor=COLOR_NEGATIVE_DARK, linewidth=0.5)
            )
        ax_cells.text(2.5, 0.05, summary, fontsize=8.5, ha="center",
                      color="#555555", style="italic")

        # Trace panel (right): per-cell traces with timing/amplitude/width
        # jitter (offsets ~120 ms, amplitude ~+/-30%, width ~+/-25%); the
        # bulk sum is overlaid in bold black.
        bulk = np.zeros_like(t)
        for amp in amps_pos:
            t_offset = rng_jitter.normal(0, 0.12)
            amp_i = amp * (1 + 0.30 * rng_jitter.normal())
            sigma_i = max(0.06, sigma_t * (1 + 0.25 * rng_jitter.normal()))
            trace_i = amp_i * np.exp(-((t - event_t - t_offset) ** 2) / (2 * sigma_i ** 2))
            ax_trace.plot(t, trace_i, color=COLOR_PHOTOMETRY,
                          linewidth=1.1, alpha=0.55)
            bulk += trace_i
        for amp in amps_neg:
            t_offset = rng_jitter.normal(0, 0.12)
            amp_i = amp * (1 + 0.30 * rng_jitter.normal())
            sigma_i = max(0.06, sigma_t * (1 + 0.25 * rng_jitter.normal()))
            trace_i = -amp_i * np.exp(-((t - event_t - t_offset) ** 2) / (2 * sigma_i ** 2))
            ax_trace.plot(t, trace_i, color=COLOR_NEGATIVE,
                          linewidth=1.1, alpha=0.55)
            bulk += trace_i

        ax_trace.plot(t, bulk, color="#1a1a1a", linewidth=2.4, zorder=5)
        ax_trace.axhline(0, color="#999", linewidth=0.4)

        ax_trace.set_xlim(0, 2)
        ax_trace.set_ylim(-4.0, 17.0)
        ax_trace.set_xticks([0, 0.5, 1.0, 1.5, 2.0])
        ax_trace.tick_params(axis="x", labelsize=8.5)
        ax_trace.tick_params(axis="y", labelsize=8.5)
        ax_trace.set_ylabel("fluorescence (a.u.)", fontsize=9)
        if index == len(configs) - 1:
            ax_trace.set_xlabel("time (s)", fontsize=9.5)
        else:
            ax_trace.set_xticklabels([])
        for spine in ["top", "right"]:
            ax_trace.spines[spine].set_visible(False)
        ax_trace.spines["left"].set_visible(True)
        ax_trace.spines["bottom"].set_visible(True)

    # Dedicated legend panel spanning both rows on the right.
    ax_legend = fig.add_subplot(gs[:, 2])
    ax_legend.set_xticks([])
    ax_legend.set_yticks([])
    for spine in ax_legend.spines.values():
        spine.set_visible(False)
    legend_handles = [
        plt.Line2D([], [], color=COLOR_PHOTOMETRY, linewidth=2.5, alpha=0.7,
                   label="positive-response\ncell"),
        plt.Line2D([], [], color=COLOR_NEGATIVE, linewidth=2.5, alpha=0.7,
                   label="negative-response\ncell"),
        plt.Line2D([], [], color="#1a1a1a", linewidth=3.0,
                   label="photometry signal"),
    ]
    ax_legend.legend(
        handles=legend_handles,
        loc="center",
        fontsize=12,
        frameon=False,
        handlelength=2.5,
        labelspacing=1.6,
        borderaxespad=0,
    )

    fig.text(
        0.5, 0.96,
        "Photometry's signal is an aggregator",
        ha="center", fontsize=14, fontweight="bold",
    )

    fig.savefig(OUT / "fig2_population_summing.svg")
    plt.close(fig)


def _draw_bracket(ax, x0, x1, y_top, y_caps_bottom, label, label_y,
                  color="#444", linewidth=1.0, label_color="#333",
                  label_fontsize=8, label_weight="normal"):
    """Draw a [-shaped bracket spanning (x0, x1) with the label below.

    Two short verticals at x0 and x1 go down from y_top to y_caps_bottom,
    and a horizontal segment at y_top connects them.
    """
    ax.plot(
        [x0, x0, x1, x1],
        [y_caps_bottom, y_top, y_top, y_caps_bottom],
        color=color, linewidth=linewidth,
    )
    ax.text(
        np.sqrt(x0 * x1) if x0 > 0 else (x0 + x1) / 2,
        label_y, label,
        fontsize=label_fontsize, ha="center", va="top",
        color=label_color, linespacing=1.15, weight=label_weight,
    )


def figure_3_space_time_landscape():
    """Place photometry against electrophysiology, two-photon imaging, and
    fMRI on a (log time x log spatial-scale) landscape.

    Recording techniques are 2D bands on (time x space). Photometry is
    rendered with visual prominence as the focal technique; the other three
    are faint italic-labelled backdrops. A gray reference frame across the
    technique-band area marks the behaviourally relevant temporal range
    (~50 ms to ~30 s). Signal-chain brackets along the time axis (action
    potential, calcium influx, GCaMP6s/6f/jGCaMP8 indicator kinetics from
    Chen et al. 2013) show the cellular landmarks the indicator transduces.
    """
    fig = plt.figure(figsize=(10.8, 7.6))
    gs = fig.add_gridspec(2, 1, height_ratios=[5.0, 1.7], hspace=0.08,
                          top=0.88, bottom=0.09, left=0.10, right=0.97)
    ax_main = fig.add_subplot(gs[0])
    ax_brackets = fig.add_subplot(gs[1], sharex=ax_main)

    # --- Main axes: techniques as (time x space) bands ---
    ax_main.set_xscale("log")
    ax_main.set_yscale("log")
    ax_main.set_xlim(0.00005, 100)
    ax_main.set_ylim(0.4, 15000)

    ax_main.set_title(
        "Photometry coordinates in space and time",
        loc="left", fontsize=11, weight="bold", color="#222222", pad=28,
    )

    ax_main.tick_params(axis="x", which="both", labelbottom=False, length=0)
    ax_main.set_yticks([1, 10, 100, 1000, 10000])
    ax_main.set_yticklabels(
        ["synapse\n~1 µm", "soma\n~10 µm", "microcircuit\n~100 µm",
         "brain region\n~1 mm", "whole brain\n~1 cm"],
        fontsize=8.5, color="#444444", linespacing=1.0,
    )
    ax_main.set_ylabel("spatial scale (log)", fontsize=9, color="#444444", labelpad=8)
    ax_main.tick_params(axis="y", which="both", length=0)
    ax_main.grid(True, which="major", linestyle=":", alpha=0.30, color="#888888")
    for s in ("bottom", "left"):
        ax_main.spines[s].set_visible(True)
        ax_main.spines[s].set_color("#888888")
        ax_main.spines[s].set_linewidth(0.8)

    # Technique bands. Photometry is given visual prominence (alpha 0.22,
    # bold non-italic label, larger fontsize) as the focal technique;
    # peers are rendered as faint italic-labelled backdrops.
    technique_bands = [
        ("electrophysiology", 0.0001, 0.1, 10, 50,
         COLOR_EPHYS, COLOR_EPHYS_DARK, 0.00025, 35, "left"),
        ("two-photon imaging", 0.01, 1.0, 1, 50,
         COLOR_TWOPHOTON, COLOR_TWOPHOTON_DARK, 0.1, 1.7, "center"),
        ("fiber photometry", BAND_X0, BAND_X1, BAND_Y0, BAND_Y1,
         COLOR_PHOTOMETRY, COLOR_PHOTOMETRY_DARK,
         float(np.sqrt(BAND_X0 * BAND_X1)),
         float(np.sqrt(BAND_Y0 * BAND_Y1)), "center"),
        ("fMRI", 1.0, 30.0, 800, 4000,
         COLOR_FMRI, COLOR_FMRI_DARK, 28, 3700, "right"),
    ]
    for name, x0, x1, y0, y1, color, edge, lx, ly, lha in technique_bands:
        is_photometry = name == "fiber photometry"
        rect_alpha = 0.22 if is_photometry else 0.09
        rect_lw = 1.4 if is_photometry else 0.5
        label_size = 11.5 if is_photometry else 8.5
        label_weight = "bold" if is_photometry else "normal"
        label_style = "normal" if is_photometry else "italic"
        ax_main.add_patch(
            Rectangle(
                (x0, y0), x1 - x0, y1 - y0,
                facecolor=color, edgecolor=edge,
                linewidth=rect_lw, alpha=rect_alpha, zorder=0,
            )
        )
        ax_main.text(
            lx, ly, name, ha=lha, va="center",
            fontsize=label_size, color=edge,
            style=label_style, weight=label_weight, zorder=1,
        )

    # Behaviourally relevant timescale: a faint gray reference frame on the
    # technique-band axes only (it stops at the time axis, not extending
    # into the signal-chain row below). Two dashed vertical boundaries and
    # a soft shaded backdrop mark the temporal range. Gray rather than
    # photometry green: this is a timescale claim about behaviour, not a
    # photometry-specific feature.
    beh_x0, beh_x1 = 0.05, 30.0
    BEH_GRAY = "#777777"
    ax_main.axvspan(beh_x0, beh_x1, facecolor=BEH_GRAY, alpha=0.06,
                    edgecolor="none", zorder=0)
    for x in (beh_x0, beh_x1):
        ax_main.axvline(x, color=BEH_GRAY, linestyle="--",
                        linewidth=1.2, zorder=4)
    # Caption sits above the title in figure-margin space (axes-y > 1.0)
    # via a hybrid transform (data x, axes y), centered on the geometric
    # mean of the dashed-line endpoints.
    ax_main.text(
        np.sqrt(beh_x0 * beh_x1), 1.08,
        "behaviourally relevant timescale",
        transform=ax_main.get_xaxis_transform(),
        ha="center", va="bottom",
        fontsize=10, color=BEH_GRAY,
        weight="bold", zorder=5,
    )

    # --- Brackets axes: signal-chain landmarks along the time axis ---
    # The time x-axis is anchored at the TOP of the brackets axes (just
    # below the technique-band area), serving as a shared horizontal
    # reference between the techniques above and the brackets below.
    ax_brackets.set_xscale("log")
    ax_brackets.set_xlim(0.00005, 100)
    ax_brackets.set_ylim(-0.55, 1.05)
    ax_brackets.set_yticks([])
    ax_brackets.set_xticks([0.0001, 0.001, 0.01, 0.1, 1, 10, 100])
    ax_brackets.set_xticklabels(
        ["0.1 ms", "1 ms", "10 ms", "100 ms", "1 s", "10 s", "100 s"],
        fontsize=8.5, color="#444444",
    )
    ax_brackets.tick_params(
        axis="x", which="both",
        bottom=False, top=True,
        labelbottom=False, labeltop=True,
        length=0,
    )
    for s in ("right", "left", "bottom"):
        ax_brackets.spines[s].set_visible(False)
    ax_brackets.spines["top"].set_visible(True)
    ax_brackets.spines["top"].set_color("#888888")
    ax_brackets.spines["top"].set_linewidth(0.8)
    ax_brackets.grid(False)

    # "time (log scale)" annotation, sitting just under the time-axis line.
    ax_brackets.text(
        np.sqrt(0.00005 * 100),
        0.99,
        "time (log scale)",
        ha="center", va="top",
        fontsize=9, color="#444444", style="italic",
    )

    # Signal-chain landmarks (cellular events the indicator transduces).
    # Indicator kinetics from Chen et al. 2013 (Nature 499:295-300).
    signal_chain = [
        (0.0008, 0.002, "action potential\n~1 ms"),
        (0.005, 0.020, "calcium influx\n~10 ms"),
        (0.022, 0.042, "jGCaMP8\n~30 ms"),
        (0.048, 0.200, "GCaMP6f\n~50-200 ms"),
        (0.220, 1.500, "GCaMP6s\n~200 ms-1.5 s"),
    ]
    for x0, x1, label in signal_chain:
        _draw_bracket(
            ax_brackets, x0, x1,
            y_top=0.82, y_caps_bottom=0.60,
            label=label, label_y=0.45,
        )

    ax_brackets.text(
        0.00004, 0.71, "signal chain",
        fontsize=8.5, ha="left", va="center",
        color="#666666", style="italic",
    )

    fig.savefig(OUT / "fig3_space_time_landscape.svg",
                facecolor="white", transparent=False)
    plt.close(fig)


if __name__ == "__main__":
    figure_2_population_summing()
    figure_3_space_time_landscape()
    print(f"Wrote figures to {OUT}")
