"""Generate stubbed testing data from the full testing_data directory.

Run from the project root:
    python scripts/create_stubbed_testing_data.py

Stub durations are hard-coded per session. For sessions with TTL events, the
duration was chosen to capture at least 5 complete TTL pulses (rising and
falling edges both within the stub window for waveform-based formats).
Sessions without TTL events use 1.0 second.

Note: NpmRecordingExtractor.stub() copies the raw source folder and truncates
raw NPM CSVs. Intermediate per-channel CSVs (chev/chod/event) are not present
in the stub — they must be regenerated by calling discover_events_and_flags()
on the stub folder before reading.
"""

from pathlib import Path

from guppy.extractors.csv_recording_extractor import CsvRecordingExtractor
from guppy.extractors.doric_recording_extractor import DoricRecordingExtractor
from guppy.extractors.npm_recording_extractor import NpmRecordingExtractor
from guppy.extractors.tdt_recording_extractor import TdtRecordingExtractor

PROJECT_ROOT = Path(__file__).parent.parent
TESTING_DATA = PROJECT_ROOT / "testing_data"
STUBBED_TESTING_DATA = PROJECT_ROOT / "stubbed_testing_data"


# ---------------------------------------------------------------------------
# Session configurations
# ---------------------------------------------------------------------------
# Each entry: (extractor_instance, stub_duration_in_seconds, destination_path)
# Durations were determined by running the full recording and finding the first
# TTL event timestamp, then adding a 0.1 s buffer.


def _sessions():
    tdt = TESTING_DATA / "SampleData_Clean"
    artifacts = TESTING_DATA / "SampleData_with_artifacts"
    doric = TESTING_DATA / "SampleData_Doric"
    npm = TESTING_DATA / "SampleData_Neurophotometrics"
    csv = TESTING_DATA / "SampleData_csv"

    dest_tdt = STUBBED_TESTING_DATA / "tdt"
    dest_doric = STUBBED_TESTING_DATA / "doric"
    dest_npm = STUBBED_TESTING_DATA / "npm"
    dest_csv = STUBBED_TESTING_DATA / "csv"

    return [
        # TDT — 5th TTL (PrtN) at ~157.4 s relative
        (
            TdtRecordingExtractor(str(tdt / "Photo_63_207-181030-103332")),
            157.5,
            dest_tdt / "Photo_63_207-181030-103332",
        ),
        # TDT — 5th TTL (PAB/) at ~215.8 s relative
        (
            TdtRecordingExtractor(str(tdt / "Photometry-161823")),
            215.9,
            dest_tdt / "Photometry-161823",
        ),
        # TDT — 5th TTL (PrtN) at ~184.2 s relative
        (
            TdtRecordingExtractor(str(artifacts / "Photo_048_392-200728-121222")),
            184.3,
            dest_tdt / "Photo_048_392-200728-121222",
        ),
        # Doric V1 — 5th TTL pulse (DI--O-1) ends at ~115.1 s
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_1"),
                {"AIn-1 - Raw": "control", "AIn-2 - Raw": "signal", "DI--O-1": "ttl"},
            ),
            115.2,
            dest_doric / "sample_doric_1",
        ),
        # Doric CSV — 5th TTL pulse (DI/O-1) ends at ~77.9 s
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_2"),
                {"AIn-1 - Dem (ref)": "control", "AIn-1 - Dem (da)": "signal", "DI/O-1": "ttl"},
            ),
            78.0,
            dest_doric / "sample_doric_2",
        ),
        # Doric V6 — 5th TTL (DigitalIO/CAM1) at ~0.1 s; 1.0 s retains many TTLs
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_3"),
                {"CAM1_EXC1/ROI01": "control", "CAM1_EXC2/ROI01": "signal", "DigitalIO/CAM1": "ttl"},
            ),
            16.0,
            dest_doric / "sample_doric_3",
        ),
        # Doric V1 — no TTL events
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_4"),
                {"Series0001/AIN01xAOUT01-LockIn": "control", "Series0001/AIN01xAOUT02-LockIn": "signal"},
            ),
            16.0,
            dest_doric / "sample_doric_4",
        ),
        # Doric V1 — no TTL events
        (
            DoricRecordingExtractor(
                str(doric / "sample_doric_5"),
                {"Series0001/AIN01xAOUT01-LockIn": "control", "Series0001/AIN01xAOUT02-LockIn": "signal"},
            ),
            16.0,
            dest_doric / "sample_doric_5",
        ),
        # CSV — 5th TTL (Sample_TTL) at ~410.9 s
        (CsvRecordingExtractor(str(csv / "sample_data_csv_1")), 411.0, dest_csv / "sample_data_csv_1"),
        # NPM v2 (LedState header) — 5th TTL (stimuli) at ~120.2 s relative
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_1")), 120.3, dest_npm / "sampleData_NPM_1"),
        # NPM v2 (LedState header, two files) — no TTL events
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_2")), 16.0, dest_npm / "sampleData_NPM_2"),
        # NPM v2 (LedState header, 4 channels) — 5th TTL (ttls) at ~252.1 s relative
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_3")), 252.2, dest_npm / "sampleData_NPM_3"),
        # NPM legacy (no header, interleaved rows) — 10th TTL (ts0) at ~577.3 s relative (5 True TTLs and 5 False TTLs)
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_4")), 578.0, dest_npm / "sampleData_NPM_4"),
        # NPM legacy (no header, interleaved rows) — 5th TTL (ts0) at ~200.9 s relative
        (NpmRecordingExtractor(str(npm / "sampleData_NPM_5")), 201.0, dest_npm / "sampleData_NPM_5"),
    ]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    print(f"Writing stubbed data to: {STUBBED_TESTING_DATA}\n")
    for extractor, duration, destination in _sessions():
        modality = type(extractor).__name__.replace("RecordingExtractor", "")
        print(f"  {modality:5s} {destination.name} ({duration}s) ...", end=" ", flush=True)
        extractor.stub(folder_path=destination, duration_in_seconds=duration)
        print("done")
    print("\nDone.")


if __name__ == "__main__":
    main()
