name: PR Tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    # Synchronize, open and reopened are the default types for pull request
    # We add ready_for_review to trigger the check for changelog and full tests when ready for review is clicked
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true