name: Run Tests

on:
  workflow_call:
    inputs:
      python-versions:
        description: 'List of Python versions to use in matrix, as JSON string'
        required: true
        type: string
      os-versions:
        description: 'List of OS versions to use in matrix, as JSON string'
        required: true
        type: string
  workflow_dispatch: